Add further successful tweaks and minification steps
smh-my-head/hades pull request #1
Opened 2021-03-23 18:42 UTC by henryefranks

Note the careful use of the word 'successful' in the title there: this is everything I had in my notebook that actually worked in the end. We could add a guide to how repositioning *could* work but currently doesn't, but I don't think it's worth the effort. Just give these a once over to check it all reads ok and there aren't any mistakes/typos.

2021-03-23 20:39 UTC, eleanor-clifford requested changes
Any chance we can also get instructions for the tweaks? Nw if it will be a ton
of effort

2021-04-16 14:11 UTC, eleanor-clifford requested changes
Lol I never submitted this review, whoops

2021-04-23 13:23 UTC, tim-clifford requested changes
Looks great. just a couple things as usual

2021-04-23 13:23 UTC, tim-clifford commented on docs/minify.md
> +An important step in minimising image size is to sparsiy it. Optionally, you
```suggestion
An important step in minimising image size is to sparsify it. Optionally, you
```
smh spell right

2021-04-23 13:23 UTC, tim-clifford commented on docs/suggested-tweaks.md
> +can't go wrong with the GUI.
```suggestion
can't go wrong with the GUI. Except maybe bricking your system. Probably not
though.
```

2021-04-23 13:33 UTC, tim-clifford approved these changes
LGTM, merging

2021-04-23 13:33 UTC, merged